name: Create Release
on:
  push:
    tags:
      - 'v*.*.*'
      - '!v*-dev*'
jobs:
  release:
    uses: agile-edge/edgex-global-pipelines/.github/workflows/release.yml@stable
    permissions:
      contents: write